/* Buyer research is stored under the existing authenticated notes collection as
   entityType=buyer_prospect. This avoids a database-rules migration on the live site. */
(()=>{
'use strict';
const $=id=>document.getElementById(id);
const core=window.BBCORBuyerCore;
let feed=null,feedError='',feedLoading=false,feedLoaded=false,discovery={candidates:[]};
const feedBase='https://raw.githubusercontent.com/robmorris74/bbcor-command-center/main/data/';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const properties=['810 Burke','710 W 8th','2801 S Horton','1920 Huntington'];
const fields={company:'Company',buyerType:'Buyer type',priority:'Priority',propertyMatch:'Candidate property match (unconfirmed)',decisionMaker:'Decision maker',role:'Role',directEmail:'Direct email',emailVerification:'Direct email verification',generalEmail:'General / acquisition email',phone:'Published phone',contactRoute:'Contact route',whyFits:'Why it fits',caveat:'Qualification / speed caveat',sourceUrl:'Source URL',compiled:'Compiled',outreachStatus:'Outreach status'};
const choices=['Research only','Review fit','Ready after approval','Contacted','In discussion','Declined','Closed'];
let context,selected='',filter={q:'',property:'',type:'',priority:'',status:''};
const records=()=>core.merged(context.notes,feed).sort((a,b)=>({High:0,Medium:1,Low:2}[priority(a)]??3)-({High:0,Medium:1,Low:2}[priority(b)]??3)||a.company.localeCompare(b.company));
const direct=r=>/direct buyer|direct developer|owner.operator|acquisition firm|direct investor/i.test(r.buyerType||'')&&!/broker/i.test(r.buyerType||'');
const verifiedEmail=r=>r.directEmail&&/published|verified|public|official/i.test(r.emailVerification||'')&&!/no verified|unverified|not verified/i.test(r.emailVerification||'');
const link=v=>{try{const u=new URL(v);return ['https:','http:'].includes(u.protocol)?u.href:''}catch{return''}};
const priority=r=>/^high/i.test(r.priority||'')?'High':/^medium/i.test(r.priority||'')?'Medium':/^low/i.test(r.priority||'')?'Low':'Research';
const slug=s=>String(s||'').toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'').slice(0,60);
const idFor=s=>{let h=2166136261;for(const c of String(s).toLowerCase())h=Math.imul(h^c.charCodeAt(0),16777619);return 'buyer_'+slug(s)+'_'+(h>>>0).toString(36)};
const get=(r,label)=>String(r[label]??'').trim();
const mapRow=r=>Object.fromEntries(Object.entries(fields).map(([key,label])=>[key,get(r,label)]));
const status=r=>r.stage||'Research only';
function render(ctx){context=ctx;if(!feedLoaded&&!feedLoading){feedLoaded=true;loadFeed();}const all=records();const high=all.filter(r=>priority(r)==='High').length;const directCount=all.filter(direct).length;const emailCount=all.filter(verifiedEmail).length;
 $('view').innerHTML=`<div class="buyer-hero"><div><div class="buyer-eyebrow">BBCOR · ACQUISITIONS RESEARCH</div><h1>Fort Scott buyer pipeline</h1><p>Research workspace for potential purchasers of candidate commercial properties.</p></div><div class="buyer-hold"><b>Outreach on hold</b><span>Sale list unconfirmed. Rob must confirm the properties and authorize outreach before any approach.</span></div></div>
 <section class="notice info"><b>Source-backed research</b><p>${feed?`${feed.prospects.length} source profiles · checked ${esc(feed.updatedAt||'date unknown')} · ${(feed.sourceErrors||[]).length} source warnings`:'Loading official-source research…'}${feedError?' · '+esc(feedError):''}</p><p>New profiles and changes require review. Private notes and stages are preserved. Source verification does not confirm interest in your properties.</p><button class="btn secondary" id="buyerRefresh" ${feedLoading?'disabled':''}>Refresh source feed</button></section>
 <section class="buyer-properties">${properties.map(p=>`<button type="button" class="buyer-property ${filter.property===p?'selected':''}" data-property-card="${esc(p)}"><span>Candidate property</span><b>${esc(p)}</b><small>${p==='2801 S Horton'?'88,000 SF · owner-provided':'Sale details unconfirmed'}</small></button>`).join('')}</section>
 <section class="buyer-stats"><div><span>Prospects</span><strong>${all.length}</strong><small>Saved records + source candidates</small></div><div><span>High priority</span><strong>${high}</strong><small>Research classification</small></div><div><span>Direct buyers / developers</span><strong>${directCount}</strong><small>Broker routes separate</small></div><div><span>Published direct emails</span><strong>${emailCount}</strong><small>See verification notes</small></div></section>
 <section class="buyer-section"><div class="buyer-heading"><div><h2>Prospect directory</h2><p>Source links, contacts, fit, qualification gaps, and follow-up status in one place.</p></div><div class="buyer-actions"><button class="btn secondary" id="buyerExport" ${all.length?'':'disabled'}>Export workbook</button>${ctx.canWrite?'<button class="btn secondary" id="buyerAdd">+ Add prospect</button><label class="btn buyer-import">Import buyer workbook<input id="buyerFile" type="file" accept=".xlsx,.xls,.csv" hidden></label>':''}</div></div>
 <div class="buyer-filters"><input id="buyerSearch" type="search" placeholder="Search firm, contact, property, or fit…" value="${esc(filter.q)}" aria-label="Search buyer prospects"><select id="buyerProperty"><option value="">All properties</option>${properties.map(p=>`<option value="${esc(p)}" ${filter.property===p?'selected':''}>${esc(p)}</option>`).join('')}</select><select id="buyerType"><option value="">All buyer types</option><option value="direct" ${filter.type==='direct'?'selected':''}>Direct buyers</option><option value="broker" ${filter.type==='broker'?'selected':''}>Brokers / intermediaries</option></select><select id="buyerPriority"><option value="">All priorities</option>${['High','Medium','Low'].map(p=>`<option ${filter.priority===p?'selected':''}>${p}</option>`).join('')}</select><select id="buyerStatus"><option value="">All stages</option>${choices.map(p=>`<option ${filter.status===p?'selected':''}>${p}</option>`).join('')}</select></div>
 <div id="buyerWorkspace"></div></section>`;
 $('buyerSearch').oninput=e=>{filter.q=e.target.value;draw()};for(const [id,key] of [['buyerProperty','property'],['buyerType','type'],['buyerPriority','priority'],['buyerStatus','status']])$(id).onchange=e=>{filter[key]=e.target.value;draw()};
 document.querySelectorAll('[data-property-card]').forEach(b=>b.onclick=()=>{filter.property=filter.property===b.dataset.propertyCard?'':b.dataset.propertyCard;render(ctx)});
 $('buyerRefresh').onclick=()=>loadFeed();$('buyerExport').onclick=exportWorkbook;if(ctx.canWrite){$('buyerFile').onchange=importWorkbook;$('buyerAdd').onclick=()=>editProspect(null)};draw();renderDiscovery();}
function filtered(){return records().filter(r=>(!filter.q||[r.company,r.buyerType,r.decisionMaker,r.propertyMatch,r.whyFits,r.contactRoute].join(' ').toLowerCase().includes(filter.q.toLowerCase()))&&(!filter.property||String(r.propertyMatch||'').toLowerCase().includes(filter.property.toLowerCase()))&&(!filter.type||(filter.type==='direct'?direct(r):/broker|intermediar/i.test(r.buyerType||'')))&&(!filter.priority||priority(r)===filter.priority)&&(!filter.status||status(r)===filter.status))}
function draw(){const rows=filtered();if(selected&&!rows.some(r=>r.id===selected))selected='';$('buyerWorkspace').innerHTML=`<div class="buyer-count">${rows.length} matching prospect${rows.length===1?'':'s'}</div><div class="buyer-layout"><div class="buyer-list">${rows.map(r=>`<button type="button" class="buyer-row ${selected===r.id?'active':''}" data-buyer="${esc(r.id)}"><span class="buyer-row-top"><b>${esc(r.company)}</b><span class="buyer-priority ${esc(priority(r).toLowerCase())}">${esc(priority(r))}</span></span><span class="buyer-row-sub">${esc(r.buyerType||'Type unconfirmed')} · ${esc(r.propertyMatch||'Match unconfirmed')}</span><span class="buyer-row-bottom"><span>${esc(r.decisionMaker||'Decision maker unconfirmed')}</span><em>${esc(status(r))}</em></span></button>`).join('')||'<div class="buyer-empty">No prospects match these filters. Clear the filters or refresh the source feed. Saved records remain available if the feed is unavailable.</div>'}</div><div id="buyerDetail" class="buyer-detail">${selected?detail(rows.find(r=>r.id===selected)):'<div class="buyer-select"><div class="buyer-select-icon">◎</div><h3>Select a prospect</h3><p>Review the contact route, source, fit, and open questions before making a decision.</p></div>'}</div></div>`;
 document.querySelectorAll('[data-buyer]').forEach(b=>b.onclick=()=>{selected=b.dataset.buyer;draw()});const review=$('buyerReviewSource');if(review)review.onclick=()=>reviewSource(selected);const edit=$('buyerEdit');if(edit)edit.onclick=()=>editProspect(selected);const stage=$('buyerStage');if(stage)stage.onchange=()=>saveStage(selected,stage.value);const save=$('buyerSaveNote');if(save)save.onclick=()=>saveNote(selected);}
function detail(r){if(!r)return'';const urls=String(r.sourceUrl||'').split(/\s*\|\s*/).map(link).filter(Boolean),hasContact=r.directEmail||r.generalEmail||r.phone;return `<div class="buyer-detail-head"><div><span class="buyer-eyebrow">PROSPECT PROFILE</span><h2>${esc(r.company)}</h2><p>${esc(r.buyerType||'Buyer type unconfirmed')}</p></div>${context.canWrite?'<button class="btn secondary small" id="buyerEdit">Edit</button>':''}</div><div class="buyer-tags"><span class="buyer-priority ${esc(priority(r).toLowerCase())}">${esc(priority(r))} priority</span><span class="badge">${direct(r)?'Direct buyer / developer':/broker/i.test(r.buyerType||'')?'Broker / intermediary':'Type to verify'}</span></div><div class="buyer-detail-grid"><div><small>Candidate match</small><b>${esc(r.propertyMatch||'Unconfirmed')}</b></div><div><small>Decision maker</small><b>${esc(r.decisionMaker||'Not verified')}</b><span>${esc(r.role||'')}</span></div></div>${sourcePanel(r)}<h3>Contact route</h3>${hasContact?`<div class="buyer-contact">${r.directEmail?`<div><small>Direct email</small><b>${esc(r.directEmail)}</b><span>${esc(r.emailVerification||'Verification not stated')}</span></div>`:''}${r.generalEmail?`<div><small>General / acquisition email</small><b>${esc(r.generalEmail)}</b></div>`:''}${r.phone?`<div><small>Published phone</small><b>${esc(r.phone)}</b></div>`:''}</div>`:'<p class="muted">No verified email or phone in the research file.</p>'}<p class="buyer-route">${esc(r.contactRoute||'Contact route unconfirmed')}</p><h3>Reason for fit</h3><p>${esc(r.whyFits||'No fit evidence recorded.')}</p><h3>Qualification gap</h3><p>${esc(r.caveat||'Acquisition criteria and timing need confirmation.')}</p><div class="buyer-source"><small>Research source · compiled ${esc(r.compiled||'date unrecorded')}</small>${urls.length?urls.map((url,i)=>`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">Source ${i+1} ↗</a>`).join(' '):'<span>Source URL unavailable</span>'}</div><div class="buyer-followup"><h3>Internal follow-up</h3><label for="buyerStage">Stage</label><select id="buyerStage" ${context.canWrite?'':'disabled'}>${choices.map(x=>`<option ${status(r)===x?'selected':''}>${x}</option>`).join('')}</select><label for="buyerNote">Next action / notes</label><textarea id="buyerNote" ${context.canWrite?'':'readonly'} placeholder="Record qualification questions and next steps…">${esc(r.internalNotes||'')}</textarea>${context.canWrite?'<button id="buyerSaveNote" class="btn secondary">Save note</button>':''}<p class="buyer-original">Workbook status: ${esc(r.outreachStatus||'Hold pending authorization')}</p></div>`}
async function saveStage(id,value){const r=records().find(x=>x.id===id);if(!r)return;try{await savePrivate(r,{stage:value});await context.audit('update buyer stage',r.company+' → '+value);context.flash('Stage saved.')}catch(e){context.flash('Could not save stage: '+e.message,'error')}}
async function saveNote(id){const r=records().find(x=>x.id===id);if(!r)return;try{await savePrivate(r,{internalNotes:$('buyerNote').value});await context.audit('update buyer note',r.company);context.flash('Note saved.')}catch(e){context.flash('Could not save note: '+e.message,'error')}}
async function importWorkbook(e){const file=e.target.files[0];if(!file)return;try{if(!window.XLSX)throw Error('Spreadsheet reader is unavailable. Reload and try again.');const wb=XLSX.read(await file.arrayBuffer(),{type:'array'});const sheet=wb.Sheets['Buyer Contacts']||wb.Sheets[wb.SheetNames[0]];if(!sheet)throw Error('No worksheet found.');let rows=XLSX.utils.sheet_to_json(sheet,{range:3,defval:'',raw:false});if(!rows.some(r=>get(r,'Company')))rows=XLSX.utils.sheet_to_json(sheet,{defval:'',raw:false});rows=rows.filter(r=>get(r,'Company'));if(!rows.length||!Object.hasOwn(rows[0],'Buyer type')||!Object.hasOwn(rows[0],'Source URL'))throw Error('Use the Fort Scott Buyer Contacts workbook with Company, Buyer type, and Source URL columns.');const ok=await context.confirmAction('Import buyer research',`Merge ${rows.length} rows into the BBCOR buyer workspace? Existing internal stages and notes will be kept. No outreach will be sent.`,'Import');if(!ok)return;const grouped=new Map();let duplicates=0;for(const row of rows){const mapped=mapRow(row),key=core.nameKey(mapped.company);if(grouped.has(key)){duplicates++;const prior=grouped.get(key);for(const k of ['propertyMatch','sourceUrl','whyFits','caveat'])prior[k]=[...new Set([prior[k],mapped[k]].filter(Boolean))].join(k==='sourceUrl'?' | ':'; ');for(const [k,v] of Object.entries(mapped))if(!prior[k])prior[k]=v;}else grouped.set(key,mapped);}const existing=Object.entries(context.notes||{}).filter(([,r])=>r.entityType==='buyer_prospect').map(([id,r])=>({id,...r}));for(const mapped of grouped.values()){const domain=String(mapped.sourceUrl||'').split(' | ')[0];let canonicalDomain='';try{canonicalDomain=new URL(domain).hostname.replace(/^www\./,'')}catch{}const candidate={...mapped,canonicalDomain},hits=existing.filter(r=>core.matches(r,candidate));if(hits.length>1)throw Error('Multiple existing profiles for '+mapped.company+'; resolve duplicates first.');const id=hits[0]?.id||idFor(mapped.company);const result=await context.db.ref('notes/'+id).transaction(prior=>{if(prior&&prior.entityType!=='buyer_prospect')return;return {...(prior||{}),...mapped,entityType:'buyer_prospect',stage:prior?.stage||'Research only',internalNotes:prior?.internalNotes||'',outreachStatus:prior?.outreachStatus||core.hold,createdAt:prior?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()}});if(!result.committed)throw Error('Record identity conflict');}await context.audit('import buyer prospects',`${grouped.size} organizations from ${file.name}`);context.flash(`${grouped.size} buyer profiles imported.${duplicates?' '+duplicates+' duplicate company row(s) skipped.':''}`)}catch(err){console.error(err);context.flash('Import stopped: '+err.message,'error')}finally{e.target.value=''}}
function editProspect(id){const r=id?records().find(x=>x.id===id)||{}:{};const editFields=['company','buyerType','priority','propertyMatch','decisionMaker','role','directEmail','emailVerification','generalEmail','phone','contactRoute','whyFits','caveat','sourceUrl','compiled'];context.modal(id?'Edit buyer prospect':'Add buyer prospect',`<form id="buyerForm" class="buyer-form"><div class="form-grid">${editFields.map(k=>`<div class="${['whyFits','caveat'].includes(k)?'full':''}"><label>${esc(fields[k])}</label>${['whyFits','caveat'].includes(k)?`<textarea name="${k}">${esc(r[k]||'')}</textarea>`:`<input name="${k}" ${k==='company'?'required':''} value="${esc(r[k]||'')}">`}</div>`).join('')}</div><div class="actions end"><button type="button" class="btn secondary" id="buyerCancel">Cancel</button><button class="btn">Save prospect</button></div></form>`);$('buyerCancel').onclick=context.closeModal;$('buyerForm').onsubmit=async e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));const newId=id||idFor(o.company);if(!id&&context.notes[newId])return context.flash('A prospect with this company name already exists.','error');try{await context.db.ref('notes/'+newId).transaction(current=>{if(current&&current.entityType!=='buyer_prospect')return;return {...(current||core.research(r)),...o,entityType:'buyer_prospect',outreachStatus:current?.outreachStatus||core.hold,stage:current?.stage||'Research only',internalNotes:current?.internalNotes||'',createdAt:current?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()}}).then(result=>{if(!result.committed)throw Error('Identity conflict; record not saved')});await context.audit(id?'edit buyer prospect':'add buyer prospect',o.company);selected=newId;context.closeModal();context.flash('Prospect saved.')}catch(err){context.flash('Could not save prospect: '+err.message,'error')}}}
function exportWorkbook(){const rows=records().map(r=>({...Object.fromEntries(Object.entries(fields).map(([k,label])=>[label,r[k]||''])),Stage:status(r),'Internal notes':r.internalNotes||'','Source review':r.sourceNeedsReview?'Pending review':'Reviewed / manual record','Source verification':r.sourceProposal?.sourceVerification?.status||r.sourceVerification?.status||'Unrecorded'}));if(!rows.length)return;const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),'Buyer Contacts');XLSX.writeFile(wb,'BBCOR_Fort_Scott_Buyer_Prospects_'+new Date().toISOString().slice(0,10)+'.xlsx');context.audit('export buyer prospects',`${rows.length} organizations`)}
async function loadFeed(){if(feedLoading)return;feedLoading=true;try{const response=await fetch(feedBase+'buyer-prospects.json?ts='+Date.now(),{cache:'no-store'});if(!response.ok)throw Error('Source feed unavailable');const value=await response.json();if(value.schemaVersion!==1||value.outboundContactLocked!==true||!Array.isArray(value.prospects)||value.prospects.length>1000||value.prospects.some(p=>!p.company||!p.sourceKey||!link(p.sourceUrl)))throw Error('Source feed failed validation');for(const p of value.prospects){const age=Date.now()-Date.parse(p.sourceVerification?.lastVerifiedAt||'');if(!Number.isFinite(age)||age>72*60*60*1000)p.sourceVerification={...(p.sourceVerification||{}),status:'stale — verification older than 72 hours'};}feed=value;feedError='';try{const d=await fetch(feedBase+'buyer-discovery.json?ts='+Date.now(),{cache:'no-store'});if(d.ok){const v=await d.json();if(Array.isArray(v.candidates))discovery=v;}}catch{} }catch(e){feedError=e.message+'; saved profiles are retained.';}finally{feedLoading=false;if(context)render(context);}}
function sourcePanel(r){const p=r.sourceProposal;if(!p)return'';const v=p.sourceVerification||{};return `<section class="notice info"><b>${r.feedOnly?'New source prospect':r.sourceNeedsReview?'Source update pending review':'Source research reviewed'}</b><p>${esc(v.status||'Unverified')} · last verified ${esc(v.lastVerifiedAt||'unknown')}</p><p>${esc(p.whyFits||'')} ${esc(p.caveat||'')}</p><p>Latest contact route: ${esc([p.generalEmail,p.phone].filter(Boolean).join(' · ')||'Review official source')}</p><p>Saved contacts and property matches change only after review. Stale evidence requires rechecking.</p>${context.canWrite&&r.sourceNeedsReview?'<button class="btn secondary" id="buyerReviewSource">Review and save source research</button>':''}</section>`;}
async function reviewSource(id){const r=records().find(x=>x.id===id),p=r?.sourceProposal;if(!context.canWrite||!p)return;if(p.sourceVerification?.status!=='verified')return context.flash('Recheck the stale source before accepting it.','error');if(!await context.confirmAction('Review source research',`Save the displayed official-source research for ${r.company}? This replaces company, type, fit evidence, caveat, source and source route. Private notes, stage, all saved contacts, priority and property match are preserved. Outreach remains on hold.`,'Save reviewed research'))return;try{const result=await context.db.ref('notes/'+id).transaction(current=>{if(current&&current.entityType!=='buyer_prospect')return;return core.reviewed(current,p,context.user?.uid||firebase.auth().currentUser.uid,new Date().toISOString())});if(!result.committed)throw Error('Record identity conflict');await context.audit('review buyer source',p.company+' · '+p.sourceVersion);context.flash('Source research saved. Outreach remains on hold.')}catch(e){context.flash('Review stopped: '+e.message,'error')}}
async function savePrivate(r,changes){if(!context.canWrite)throw Error('Write access required');const result=await context.db.ref('notes/'+r.id).transaction(current=>{if(current&&current.entityType!=='buyer_prospect')return;return {...(current||core.research(r)),entityType:'buyer_prospect',priority:current?.priority||'Research',propertyMatch:current?.propertyMatch||'Unconfirmed — review acquisition criteria',stage:current?.stage||'Research only',outreachStatus:current?.outreachStatus||core.hold,createdAt:current?.createdAt||new Date().toISOString(),...changes,updatedAt:new Date().toISOString()}});if(!result.committed)throw Error('Identity conflict');}
function renderDiscovery(){const rows=(discovery.candidates||[]).filter(c=>link(c.url)).slice(0,100);if(!rows.length)return;const el=document.createElement('section');el.className='buyer-section';el.innerHTML=`<h2>Discovery review queue</h2><p>Search results awaiting official-source verification. These are not counted as verified prospects.</p>${rows.map(c=>`<p><a href="${esc(link(c.url))}" target="_blank" rel="noopener noreferrer">${esc(c.title||c.url)}</a> · ${esc(c.status)}</p>`).join('')}`;$('view').appendChild(el);}
setInterval(()=>{if(context&&document.body.dataset.center==='buyers'&&!document.getElementById('appShell')?.classList.contains('hidden'))loadFeed();},2*60*60*1000);
window.BBCORBuyers={render};
})();

