/* Buyer research is stored under the existing authenticated notes collection as
   entityType=buyer_prospect. This avoids a database-rules migration on the live site. */
(()=>{
'use strict';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const properties=['810 Burke','710 W 8th','2801 S Horton','1920 Huntington'];
const fields={company:'Company',buyerType:'Buyer type',priority:'Priority',propertyMatch:'Candidate property match (unconfirmed)',decisionMaker:'Decision maker',role:'Role',directEmail:'Direct email',emailVerification:'Direct email verification',generalEmail:'General / acquisition email',phone:'Published phone',contactRoute:'Contact route',whyFits:'Why it fits',caveat:'Qualification / speed caveat',sourceUrl:'Source URL',compiled:'Compiled',outreachStatus:'Outreach status'};
const choices=['Research only','Review fit','Ready after approval','Contacted','In discussion','Declined','Closed'];
let context,selected='',filter={q:'',property:'',type:'',priority:'',status:''};
const records=()=>Object.entries(context.notes||{}).filter(([,r])=>r&&r.entityType==='buyer_prospect').map(([id,r])=>({id,...r})).sort((a,b)=>({High:0,Medium:1,Low:2}[priority(a)]??3)-({High:0,Medium:1,Low:2}[priority(b)]??3)||a.company.localeCompare(b.company));
const direct=r=>/direct buyer|direct developer|owner.operator|acquisition firm|direct investor/i.test(r.buyerType||'')&&!/broker/i.test(r.buyerType||'');
const verifiedEmail=r=>r.directEmail&&/published|verified|public|official/i.test(r.emailVerification||'')&&!/no verified|unverified|not verified/i.test(r.emailVerification||'');
const link=v=>{try{const u=new URL(v);return ['https:','http:'].includes(u.protocol)?u.href:''}catch{return''}};
const priority=r=>/^high/i.test(r.priority||'')?'High':/^medium/i.test(r.priority||'')?'Medium':/^low/i.test(r.priority||'')?'Low':'Research';
const slug=s=>String(s||'').toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'').slice(0,60);
const idFor=s=>{let h=2166136261;for(const c of String(s).toLowerCase())h=Math.imul(h^c.charCodeAt(0),16777619);return 'buyer_'+slug(s)+'_'+(h>>>0).toString(36)};
const get=(r,label)=>String(r[label]??'').trim();
const mapRow=r=>Object.fromEntries(Object.entries(fields).map(([key,label])=>[key,get(r,label)]));
const status=r=>r.stage||'Research only';
function render(ctx){context=ctx;const all=records();const high=all.filter(r=>priority(r)==='High').length;const directCount=all.filter(direct).length;const emailCount=all.filter(verifiedEmail).length;
 $('view').innerHTML=`<div class="buyer-hero"><div><div class="buyer-eyebrow">BBCOR · ACQUISITIONS RESEARCH</div><h1>Fort Scott buyer pipeline</h1><p>Research workspace for potential purchasers of candidate commercial properties.</p></div><div class="buyer-hold"><b>Outreach on hold</b><span>Sale list unconfirmed. Rob must confirm the properties and authorize outreach before any approach.</span></div></div>
 <section class="buyer-properties">${properties.map(p=>`<button type="button" class="buyer-property ${filter.property===p?'selected':''}" data-property-card="${esc(p)}"><span>Candidate property</span><b>${esc(p)}</b><small>${p==='2801 S Horton'?'88,000 SF · owner-provided':'Sale details unconfirmed'}</small></button>`).join('')}</section>
 <section class="buyer-stats"><div><span>Prospects</span><strong>${all.length}</strong><small>In private workspace</small></div><div><span>High priority</span><strong>${high}</strong><small>Research classification</small></div><div><span>Direct buyers / developers</span><strong>${directCount}</strong><small>Broker routes separate</small></div><div><span>Published direct emails</span><strong>${emailCount}</strong><small>See verification notes</small></div></section>
 <section class="buyer-section"><div class="buyer-heading"><div><h2>Prospect directory</h2><p>Source links, contacts, fit, qualification gaps, and follow-up status in one place.</p></div><div class="buyer-actions"><button class="btn secondary" id="buyerExport" ${all.length?'':'disabled'}>Export workbook</button>${ctx.canWrite?'<button class="btn secondary" id="buyerAdd">+ Add prospect</button><label class="btn buyer-import">Import buyer workbook<input id="buyerFile" type="file" accept=".xlsx,.xls,.csv" hidden></label>':''}</div></div>
 <div class="buyer-filters"><input id="buyerSearch" type="search" placeholder="Search firm, contact, property, or fit…" value="${esc(filter.q)}" aria-label="Search buyer prospects"><select id="buyerProperty"><option value="">All properties</option>${properties.map(p=>`<option value="${esc(p)}" ${filter.property===p?'selected':''}>${esc(p)}</option>`).join('')}</select><select id="buyerType"><option value="">All buyer types</option><option value="direct" ${filter.type==='direct'?'selected':''}>Direct buyers</option><option value="broker" ${filter.type==='broker'?'selected':''}>Brokers / intermediaries</option></select><select id="buyerPriority"><option value="">All priorities</option>${['High','Medium','Low'].map(p=>`<option ${filter.priority===p?'selected':''}>${p}</option>`).join('')}</select><select id="buyerStatus"><option value="">All stages</option>${choices.map(p=>`<option ${filter.status===p?'selected':''}>${p}</option>`).join('')}</select></div>
 <div id="buyerWorkspace"></div></section>`;
 $('buyerSearch').oninput=e=>{filter.q=e.target.value;draw()};for(const [id,key] of [['buyerProperty','property'],['buyerType','type'],['buyerPriority','priority'],['buyerStatus','status']])$(id).onchange=e=>{filter[key]=e.target.value;draw()};
 document.querySelectorAll('[data-property-card]').forEach(b=>b.onclick=()=>{filter.property=filter.property===b.dataset.propertyCard?'':b.dataset.propertyCard;render(ctx)});
 $('buyerExport').onclick=exportWorkbook;if(ctx.canWrite){$('buyerFile').onchange=importWorkbook;$('buyerAdd').onclick=()=>editProspect(null)};draw();}
function filtered(){return records().filter(r=>(!filter.q||[r.company,r.buyerType,r.decisionMaker,r.propertyMatch,r.whyFits,r.contactRoute].join(' ').toLowerCase().includes(filter.q.toLowerCase()))&&(!filter.property||String(r.propertyMatch||'').toLowerCase().includes(filter.property.toLowerCase()))&&(!filter.type||(filter.type==='direct'?direct(r):/broker|intermediar/i.test(r.buyerType||'')))&&(!filter.priority||priority(r)===filter.priority)&&(!filter.status||status(r)===filter.status))}
function draw(){const rows=filtered();if(selected&&!rows.some(r=>r.id===selected))selected='';$('buyerWorkspace').innerHTML=`<div class="buyer-count">${rows.length} matching prospect${rows.length===1?'':'s'}</div><div class="buyer-layout"><div class="buyer-list">${rows.map(r=>`<button type="button" class="buyer-row ${selected===r.id?'active':''}" data-buyer="${esc(r.id)}"><span class="buyer-row-top"><b>${esc(r.company)}</b><span class="buyer-priority ${esc(priority(r).toLowerCase())}">${esc(priority(r))}</span></span><span class="buyer-row-sub">${esc(r.buyerType||'Type unconfirmed')} · ${esc(r.propertyMatch||'Match unconfirmed')}</span><span class="buyer-row-bottom"><span>${esc(r.decisionMaker||'Decision maker unconfirmed')}</span><em>${esc(status(r))}</em></span></button>`).join('')||'<div class="buyer-empty">No prospects match these filters. Import the buyer contacts workbook to populate this workspace.</div>'}</div><div id="buyerDetail" class="buyer-detail">${selected?detail(rows.find(r=>r.id===selected)):'<div class="buyer-select"><div class="buyer-select-icon">◎</div><h3>Select a prospect</h3><p>Review the contact route, source, fit, and open questions before making a decision.</p></div>'}</div></div>`;
 document.querySelectorAll('[data-buyer]').forEach(b=>b.onclick=()=>{selected=b.dataset.buyer;draw()});const edit=$('buyerEdit');if(edit)edit.onclick=()=>editProspect(selected);const stage=$('buyerStage');if(stage)stage.onchange=()=>saveStage(selected,stage.value);const save=$('buyerSaveNote');if(save)save.onclick=()=>saveNote(selected);}
function detail(r){if(!r)return'';const urls=String(r.sourceUrl||'').split(/\s*\|\s*/).map(link).filter(Boolean),hasContact=r.directEmail||r.generalEmail||r.phone;return `<div class="buyer-detail-head"><div><span class="buyer-eyebrow">PROSPECT PROFILE</span><h2>${esc(r.company)}</h2><p>${esc(r.buyerType||'Buyer type unconfirmed')}</p></div>${context.canWrite?'<button class="btn secondary small" id="buyerEdit">Edit</button>':''}</div><div class="buyer-tags"><span class="buyer-priority ${esc(priority(r).toLowerCase())}">${esc(priority(r))} priority</span><span class="badge">${direct(r)?'Direct buyer / developer':/broker/i.test(r.buyerType||'')?'Broker / intermediary':'Type to verify'}</span></div><div class="buyer-detail-grid"><div><small>Candidate match</small><b>${esc(r.propertyMatch||'Unconfirmed')}</b></div><div><small>Decision maker</small><b>${esc(r.decisionMaker||'Not verified')}</b><span>${esc(r.role||'')}</span></div></div><h3>Contact route</h3>${hasContact?`<div class="buyer-contact">${r.directEmail?`<div><small>Direct email</small><b>${esc(r.directEmail)}</b><span>${esc(r.emailVerification||'Verification not stated')}</span></div>`:''}${r.generalEmail?`<div><small>General / acquisition email</small><b>${esc(r.generalEmail)}</b></div>`:''}${r.phone?`<div><small>Published phone</small><b>${esc(r.phone)}</b></div>`:''}</div>`:'<p class="muted">No verified email or phone in the research file.</p>'}<p class="buyer-route">${esc(r.contactRoute||'Contact route unconfirmed')}</p><h3>Reason for fit</h3><p>${esc(r.whyFits||'No fit evidence recorded.')}</p><h3>Qualification gap</h3><p>${esc(r.caveat||'Acquisition criteria and timing need confirmation.')}</p><div class="buyer-source"><small>Research source · compiled ${esc(r.compiled||'date unrecorded')}</small>${urls.length?urls.map((url,i)=>`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">Source ${i+1} ↗</a>`).join(' '):'<span>Source URL unavailable</span>'}</div><div class="buyer-followup"><h3>Internal follow-up</h3><label for="buyerStage">Stage</label><select id="buyerStage" ${context.canWrite?'':'disabled'}>${choices.map(x=>`<option ${status(r)===x?'selected':''}>${x}</option>`).join('')}</select><label for="buyerNote">Next action / notes</label><textarea id="buyerNote" ${context.canWrite?'':'readonly'} placeholder="Record qualification questions and next steps…">${esc(r.internalNotes||'')}</textarea>${context.canWrite?'<button id="buyerSaveNote" class="btn secondary">Save note</button>':''}<p class="buyer-original">Workbook status: ${esc(r.outreachStatus||'Hold pending authorization')}</p></div>`}
async function saveStage(id,value){const r=context.notes[id];if(!r)return;try{await context.db.ref('notes/'+id).update({stage:value,updatedAt:new Date().toISOString()});await context.audit('update buyer stage',r.company+' → '+value);context.flash('Stage saved.')}catch(e){context.flash('Could not save stage: '+e.message,'error')}}
async function saveNote(id){const r=context.notes[id];if(!r)return;try{await context.db.ref('notes/'+id).update({internalNotes:$('buyerNote').value,updatedAt:new Date().toISOString()});await context.audit('update buyer note',r.company);context.flash('Note saved.')}catch(e){context.flash('Could not save note: '+e.message,'error')}}
async function importWorkbook(e){const file=e.target.files[0];if(!file)return;try{if(!window.XLSX)throw Error('Spreadsheet reader is unavailable. Reload and try again.');const wb=XLSX.read(await file.arrayBuffer(),{type:'array'});const sheet=wb.Sheets['Buyer Contacts']||wb.Sheets[wb.SheetNames[0]];if(!sheet)throw Error('No worksheet found.');let rows=XLSX.utils.sheet_to_json(sheet,{range:3,defval:'',raw:false});if(!rows.some(r=>get(r,'Company')))rows=XLSX.utils.sheet_to_json(sheet,{defval:'',raw:false});rows=rows.filter(r=>get(r,'Company'));if(!rows.length||!Object.hasOwn(rows[0],'Buyer type')||!Object.hasOwn(rows[0],'Source URL'))throw Error('Use the Fort Scott Buyer Contacts workbook with Company, Buyer type, and Source URL columns.');const ok=await context.confirmAction('Import buyer research',`Merge ${rows.length} rows into the BBCOR buyer workspace? Existing internal stages and notes will be kept. No outreach will be sent.`,'Import');if(!ok)return;const updates={},seen=new Set();let duplicates=0;for(const row of rows){const mapped=mapRow(row),id=idFor(mapped.company);if(seen.has(id)){duplicates++;continue}seen.add(id);const prior=context.notes[id]||{};updates['notes/'+id]={...mapped,entityType:'buyer_prospect',stage:prior.stage||'Research only',internalNotes:prior.internalNotes||'',createdAt:prior.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()}}await context.db.ref().update(updates);await context.audit('import buyer prospects',`${Object.keys(updates).length} organizations from ${file.name}`);context.flash(`${Object.keys(updates).length} buyer profiles imported.${duplicates?' '+duplicates+' duplicate company row(s) skipped.':''}`)}catch(err){console.error(err);context.flash('Import stopped: '+err.message,'error')}finally{e.target.value=''}}
function editProspect(id){const r=id?context.notes[id]||{}:{};const editFields=['company','buyerType','priority','propertyMatch','decisionMaker','role','directEmail','emailVerification','generalEmail','phone','contactRoute','whyFits','caveat','sourceUrl','compiled'];context.modal(id?'Edit buyer prospect':'Add buyer prospect',`<form id="buyerForm" class="buyer-form"><div class="form-grid">${editFields.map(k=>`<div class="${['whyFits','caveat'].includes(k)?'full':''}"><label>${esc(fields[k])}</label>${['whyFits','caveat'].includes(k)?`<textarea name="${k}">${esc(r[k]||'')}</textarea>`:`<input name="${k}" ${k==='company'?'required':''} value="${esc(r[k]||'')}">`}</div>`).join('')}</div><div class="actions end"><button type="button" class="btn secondary" id="buyerCancel">Cancel</button><button class="btn">Save prospect</button></div></form>`);$('buyerCancel').onclick=context.closeModal;$('buyerForm').onsubmit=async e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));const newId=id||idFor(o.company);if(!id&&context.notes[newId])return context.flash('A prospect with this company name already exists.','error');try{await context.db.ref('notes/'+newId).set({...r,...o,entityType:'buyer_prospect',outreachStatus:r.outreachStatus||'Hold — confirm sale list and authorize outreach',stage:r.stage||'Research only',createdAt:r.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()});await context.audit(id?'edit buyer prospect':'add buyer prospect',o.company);selected=newId;context.closeModal();context.flash('Prospect saved.')}catch(err){context.flash('Could not save prospect: '+err.message,'error')}}}
function exportWorkbook(){const rows=records().map(r=>({...Object.fromEntries(Object.entries(fields).map(([k,label])=>[label,r[k]||''])),Stage:status(r),'Internal notes':r.internalNotes||''}));if(!rows.length)return;const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),'Buyer Contacts');XLSX.writeFile(wb,'BBCOR_Fort_Scott_Buyer_Prospects_'+new Date().toISOString().slice(0,10)+'.xlsx');context.audit('export buyer prospects',`${rows.length} organizations`)}
window.BBCORBuyers={render};
})();
