/* Authenticated rental portfolio workspace. Monetary values are stored in integer cents. */
(()=>{'use strict';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x])),now=()=>new Date().toISOString(),today=()=>now().slice(0,10),money=v=>(Number(v||0)/100).toLocaleString('en-US',{style:'currency',currency:'USD'}),C=window.BBCORRentalCore;
let ctx,tab='overview',q='',propertyFilter='';
const types={properties:'rental_property',units:'rental_unit',tenants:'rental_tenant',leases:'rental_lease',charges:'rental_charge',payments:'rental_payment',maintenance:'rental_work_order',expenses:'rental_expense'};
const schemas={
properties:[['name','Property name','text',true],['address','Street address','text',true],['city','City','text'],['state','State','text'],['zip','ZIP','text'],['type','Property type',['Single family','Duplex','Multifamily','Commercial','Mixed use']],['status','Status',['Active','Hold','Sold']],['notes','Notes','textarea']],
units:[['propertyId','Property','properties',true],['name','Unit / door','text',true],['beds','Bedrooms','number'],['baths','Bathrooms','number'],['targetRentCents','Market rent','money'],['notes','Notes','textarea']],
tenants:[['name','Tenant name','text',true],['email','Email','email'],['phone','Phone','tel'],['emergencyContact','Emergency contact','text'],['notes','Notes','textarea']],
leases:[['unitId','Unit','units',true],['tenantId','Tenant','tenants',true],['startDate','Start date','date',true],['endDate','End date (blank for ongoing)','date'],['status','Status',['Active','Draft','Ended']],['rentCents','Monthly rent','money',true],['dueDay','Rent due day (1–28)','number',true],['depositRequiredCents','Required security deposit','money'],['notes','Lease notes','textarea']],
charges:[['leaseId','Lease','leases',true],['kind','Charge type',['Rent','Fee','Utility','Credit']],['dueDate','Due date','date',true],['amountCents','Amount','money',true],['description','Description','text',true]],
payments:[['leaseId','Lease','leases',true],['kind','Transaction type',['Rent payment','Rent refund','Deposit received','Deposit refund']],['date','Transaction date','date',true],['amountCents','Amount','money',true],['method','Method',['ACH','Check','Cash','Card','Other']],['reference','Check / transaction reference','text'],['notes','Notes','textarea']],
maintenance:[['propertyId','Property','properties',true],['unitId','Unit (optional)','units'],['title','Issue / work order','text',true],['priority','Priority',['Normal','High','Emergency']],['status','Status',['Open','In progress','Completed']],['reportedDate','Reported date','date',true],['dueDate','Target date','date'],['assignedTo','Vendor / assigned to','text'],['notes','Work details','textarea']],
expenses:[['propertyId','Property','properties',true],['unitId','Unit (optional)','units'],['date','Expense date','date',true],['category','Category',['Repairs','Utilities','Insurance','Taxes','Management','Capital improvement','Other']],['vendor','Vendor','text'],['amountCents','Amount','money',true],['reference','Receipt / invoice reference','text'],['notes','Notes','textarea']]
};
const rows=k=>Object.entries(ctx.notes||{}).filter(([,r])=>r?.entityType===types[k]).map(([id,r])=>({...r,id}));
const find=(k,id)=>rows(k).find(r=>r.id===id);
function label(k,r){if(!r)return 'Missing record';if(k==='units')return (find('properties',r.propertyId)?.name||'Property')+' · '+r.name;if(k==='leases')return label('units',find('units',r.unitId))+' / '+(find('tenants',r.tenantId)?.name||'Tenant');return r.name||r.title||r.description||r.id}
const equalRecords=(a,b)=>{const normalize=o=>JSON.stringify(Object.fromEntries(Object.entries(o).filter(([k])=>k!=='id').sort(([a],[b])=>a.localeCompare(b))));return normalize(a)===normalize(b)};
const filtered=k=>rows(k).filter(r=>(!propertyFilter||r.id===propertyFilter||r.propertyId===propertyFilter)&&(!q||Object.values(r).join(' ').toLowerCase().includes(q.toLowerCase())));
function render(c){ctx=c;const leases=rows('leases'),units=rows('units'),active=leases.filter(r=>C.active(r,today())),occupied=new Set(active.map(r=>r.unitId)),past=leases.reduce((s,r)=>s+C.leaseBalance(r.id,rows('charges'),rows('payments'),today()).pastDueCents,0),flow=C.cashflow(rows('payments'),rows('expenses'),today().slice(0,7)+'-01',today());
$('view').innerHTML=`<section class="hub-hero rental-hero"><span>BBCOR · RENTAL PORTFOLIO</span><h1>Rental Center</h1><p>Every property. Every lease. A clear view of your rental business.</p></section><section class="buyer-stats"><div><span>Occupancy today</span><strong>${occupied.size} / ${units.length}</strong><small>${units.length?Math.round(occupied.size/units.length*100):0}% occupied</small></div><div><span>Scheduled monthly rent</span><strong>${money(active.reduce((s,r)=>s+Number(r.rentCents||0),0))}</strong><small>Active leases today</small></div><div><span>Past-due balance</span><strong>${money(past)}</strong><small>Posted charges less rent payments</small></div><div><span>Month cash flow</span><strong>${money(flow.netCents)}</strong><small>Rent receipts less rental expenses</small></div></section><div class="admin-tabs rental-tabs" id="rentalTabs">${[['overview','Overview'],['properties','Properties'],['units','Units'],['tenants','Tenants'],['leases','Leases & rent roll'],['ledger','Rent ledger'],['maintenance','Maintenance'],['expenses','Rental expenses'],['reports','Reports & transfer']].map(([k,t])=>`<button data-tab="${k}" class="${tab===k?'active':''}">${t}</button>`).join('')}</div><div id="rentalBody"></div>`;
$('rentalTabs').onclick=x=>{const b=x.target.closest('[data-tab]');if(b){tab=b.dataset.tab;q='';render(ctx)}};
if(tab==='overview')overview();else if(tab==='ledger')ledger();else if(tab==='reports')reports();else directory(tab);
}
function overview(){const vacant=rows('units').filter(u=>!rows('leases').some(l=>l.unitId===u.id&&C.active(l,today()))),expiring=rows('leases').filter(l=>C.active(l,today())&&l.endDate&&l.endDate<=new Date(Date.now()+90*86400000).toISOString().slice(0,10)),open=rows('maintenance').filter(r=>r.status!=='Completed');$('rentalBody').innerHTML=`<div class="rental-overview"><section class="card"><h3>Portfolio attention</h3><p><b>${vacant.length}</b> vacant units · <b>${expiring.length}</b> leases ending within 90 days · <b>${open.length}</b> open work orders</p>${open.filter(r=>r.priority==='Emergency').map(r=>`<p class="notice error">Emergency: ${esc(r.title)} · ${esc(find('properties',r.propertyId)?.name)}</p>`).join('')}<h4>Upcoming lease expirations</h4>${expiring.map(l=>`<p>${esc(label('leases',l))} <b>${esc(l.endDate)}</b></p>`).join('')||'<p class="muted">No active leases expiring in the next 90 days.</p>'}</section><section class="card"><h3>Start with your portfolio</h3><p>Add a property, its units, your tenants, and their leases. Post monthly rent charges to create balances, then record payments as they arrive.</p><p class="muted">Security deposits are tracked separately from rent income. Work-order costs should be entered once in Rental expenses. Rent posting is manual; no tenant emails are sent.</p><p class="muted">Data is shared with authorized BBCOR accounts. No portfolio records have been assumed or preloaded.</p></section></div>`}
function toolbar(title,add){return `<div class="section-head"><h3>${title}</h3><div class="actions">${ctx.canWrite&&add?`<button class="btn" data-add="${add}">+ Add ${add==='properties'?'property':add==='maintenance'?'work order':add==='expenses'?'expense':add.replace(/s$/,'')}</button>`:''}</div></div><div class="rental-filters"><input id="rentalSearch" type="search" placeholder="Search this section…" aria-label="Search records" value="${esc(q)}"><select id="rentalProperty" aria-label="Filter property"><option value="">All properties</option>${rows('properties').map(p=>`<option value="${esc(p.id)}" ${p.id===propertyFilter?'selected':''}>${esc(p.name)}</option>`).join('')}</select></div><div id="rentalTable"></div>`}
function wire(){if($('rentalSearch'))$('rentalSearch').oninput=x=>{q=x.target.value;drawTable()};if($('rentalProperty'))$('rentalProperty').onchange=x=>{propertyFilter=x.target.value;drawTable()};$('rentalBody').onclick=x=>{const b=x.target.closest('button');if(!b)return;if(b.dataset.add)edit(b.dataset.add);if(b.dataset.edit)edit(b.dataset.key,b.dataset.edit);if(b.dataset.void)voidRecord(b.dataset.key,b.dataset.void)}}
function directory(k){$('rentalBody').innerHTML=toolbar(k==='leases'?'Leases & current rent roll':k==='expenses'?'Rental expenses':k.charAt(0).toUpperCase()+k.slice(1),k);wire();drawTable()}
function cell(k,r,[field,title,type]){if(type==='money')return money(r[field]);if(types[type])return esc(r[field]?label(type,find(type,r[field])):'—');if(type==='textarea')return esc(String(r[field]||'').slice(0,120));return esc(r[field]??'—')}
function drawTable(){if(tab==='ledger'){drawLedger();return}const k=tab,fields=schemas[k].filter(x=>x[0]!=='notes'&&x[0]!=='emergencyContact'),a=(k==='tenants'?rows(k).filter(r=>!q||Object.values(r).join(' ').toLowerCase().includes(q.toLowerCase())):filtered(k));$('rentalTable').innerHTML=`<div class="table-wrap"><table><thead><tr>${fields.map(x=>`<th>${esc(x[1])}</th>`).join('')}${k==='units'?'<th>Occupancy</th>':''}${k==='leases'?'<th>Balance</th><th>Past due</th><th>Deposit held / required</th>':''}<th>Actions</th></tr></thead><tbody>${a.map(r=>`<tr class="${r.voided?'rental-void':''}">${fields.map(f=>`<td>${cell(k,r,f)}</td>`).join('')}${k==='units'?`<td>${rows('leases').some(l=>l.unitId===r.id&&C.active(l,today()))?'Occupied':'Vacant'}</td>`:''}${k==='leases'?`<td>${money(C.leaseBalance(r.id,rows('charges'),rows('payments'),today()).balanceCents)}</td><td>${money(C.leaseBalance(r.id,rows('charges'),rows('payments'),today()).pastDueCents)}</td><td>${money(C.deposits(r.id,rows('payments'),today()))} / ${money(r.depositRequiredCents)}</td>`:''}<td>${r.voided?'Voided':ctx.canWrite?`<button class="btn secondary small" data-key="${k}" data-edit="${esc(r.id)}">${k==='expenses'?'View':'Edit'}</button>`:''}${ctx.isAdmin&&k==='expenses'&&!r.voided?` <button class="btn danger small" data-key="${k}" data-void="${esc(r.id)}">Void</button>`:''}</td></tr>`).join('')||`<tr><td colspan="20" class="empty">No records yet. Add your first entry to begin.</td></tr>`}</tbody></table></div>`}
function ledger(){$('rentalBody').innerHTML=toolbar('Rent & deposit ledger')+`<div class="actions rental-ledger-actions">${ctx.canWrite?'<button class="btn" id="postRent">Post monthly rent</button><button class="btn secondary" data-add="payments">Record payment / deposit</button><button class="btn secondary" data-add="charges">Add charge / credit</button>':''}</div>`;wire();if(ctx.canWrite)$('postRent').onclick=postRent;drawLedger()}
function drawLedger(){const a=[...filtered('charges').map(r=>({...r,key:'charges',date:r.dueDate})),...filtered('payments').map(r=>({...r,key:'payments'}))].sort((a,b)=>b.date.localeCompare(a.date));$('rentalTable').innerHTML=`<p class="muted">Balances apply rent payments to the lease's oldest posted charges. Deposits never reduce rent balances. Future charges are excluded until due.</p><div class="table-wrap"><table><thead><tr><th>Date</th><th>Lease</th><th>Type</th><th>Amount</th><th>Description / reference</th><th>Status</th><th>Actions</th></tr></thead><tbody>${a.map(r=>`<tr class="${r.voided?'rental-void':''}"><td>${esc(r.date)}</td><td>${esc(label('leases',find('leases',r.leaseId)))}</td><td>${esc(r.kind)}</td><td>${money(r.amountCents)}</td><td>${esc(r.description||r.reference||r.notes||'—')}</td><td>${r.voided?'Voided':'Posted'}</td><td>${ctx.isAdmin&&!r.voided?`<button class="btn danger small" data-key="${r.key}" data-void="${esc(r.id)}">Void</button>`:''}</td></tr>`).join('')||'<tr><td colspan="7" class="empty">Post rent charges, then record receipts and deposits.</td></tr>'}</tbody></table></div>`}
function input(f,r){const [key,title,type,required]=f;let value=r[key]??(type==='date'&&['date','reportedDate'].includes(key)?today():key==='dueDay'?1:'');if(type==='money'&&value!=='')value=Number(value)/100;let html;if(Array.isArray(type))html=`<select name="${key}">${type.map(v=>`<option ${v===value?'selected':''}>${esc(v)}</option>`).join('')}</select>`;else if(types[type])html=`<select name="${key}" ${required?'required':''}><option value="">Select ${title.toLowerCase()}</option>${rows(type).map(v=>`<option value="${esc(v.id)}" ${v.id===value?'selected':''}>${esc(label(type,v))}</option>`).join('')}</select>`;else if(type==='textarea')html=`<textarea name="${key}" rows="3">${esc(value)}</textarea>`;else html=`<input name="${key}" type="${type==='money'?'number':type}" ${['money','number'].includes(type)?'min="0" step="'+(type==='money'?'0.01':'0.5')+'"':''} ${key==='dueDay'?'max="28" step="1"':''} ${required?'required':''} value="${esc(value)}">`;return `<div><label>${esc(title)}</label>${html}</div>`}
function validate(k,o,id=''){for(const [field,,type,required] of schemas[k]){if(required&&(o[field]===''||o[field]===undefined))throw Error('Complete all required fields.');if(type==='date'&&o[field]&&!C.dateOk(o[field]))throw Error('Enter a valid date.');if(type==='money'&&(!Number.isSafeInteger(o[field])||o[field]<0))throw Error('Amounts must be nonnegative and use two decimal places.');if(types[type]&&o[field]&&!find(type,o[field]))throw Error('A linked record is missing.');}
if(k==='leases'){if(o.endDate&&o.endDate<o.startDate)throw Error('Lease end must follow its start.');if(!Number.isInteger(o.dueDay)||o.dueDay<1||o.dueDay>28)throw Error('Due day must be 1–28.');if(o.status==='Active'&&rows('leases').some(l=>l.id!==id&&l.status==='Active'&&l.unitId===o.unitId&&l.startDate<=(o.endDate||'9999-12-31')&&(l.endDate||'9999-12-31')>=o.startDate))throw Error('This unit already has an overlapping active lease.');}
if(['units','maintenance','expenses'].includes(k)&&o.unitId&&find('units',o.unitId)?.propertyId!==o.propertyId)throw Error('The selected unit belongs to another property.');if(['charges','payments','expenses'].includes(k)&&o.amountCents<=0)throw Error('Transaction amount must be greater than zero.');}
function edit(k,id){if(!ctx.canWrite)return;const r=find(k,id)||{};const transaction=['charges','payments','expenses'].includes(k);ctx.modal(id?'Record details':'Add '+(k==='maintenance'?'work order':({properties:'property',units:'unit',tenants:'tenant',leases:'lease',charges:'charge',payments:'payment',expenses:'expense'}[k]||k)),`<form id="rentalForm"><div class="form-grid">${schemas[k].map(f=>input(f,r)).join('')}</div><p id="rentalError" class="error"></p><div class="actions end">${id&&transaction?'<span class="muted">Posted financial entries are immutable. An administrator can void and replace a correction.</span>':'<button class="btn" type="submit">Save record</button>'}</div></form>`);if(id&&transaction){$('rentalForm').querySelectorAll('input,select,textarea').forEach(x=>x.disabled=true);return}$('rentalForm').onsubmit=async ev=>{ev.preventDefault();const button=ev.target.querySelector('button[type=submit]');button.disabled=true;try{const fd=new FormData(ev.target),o={};for(const [field,,type] of schemas[k]){const v=fd.get(field)||'';o[field]=type==='money'?C.cents(v):type==='number'?Number(v):v}validate(k,o,id);if(k==='leases')o.propertyId=find('units',o.unitId).propertyId;if(['charges','payments'].includes(k))o.propertyId=find('leases',o.leaseId).propertyId;
if(k==='units'&&id&&r.propertyId!==o.propertyId&&rows('leases').some(l=>l.unitId===id))throw Error('A leased unit cannot be moved to another property.');if(k==='leases'&&id&&(r.unitId!==o.unitId||r.tenantId!==o.tenantId)&&[...rows('charges'),...rows('payments')].some(t=>t.leaseId===id))throw Error('A lease with transactions cannot change unit or tenant. Create a new lease.');
const key=id||'rental_'+k+'_'+ctx.db.ref('notes').push().key;await ctx.db.ref('notes/'+key).set({...r,...o,entityType:types[k],createdAt:r.createdAt||now(),updatedAt:now(),updatedBy:ctx.user.uid});await ctx.audit('save rental '+k,key);ctx.closeModal();ctx.flash('Rental record saved.')}catch(err){$('rentalError').textContent=err.message;button.disabled=false}}}
async function voidRecord(k,id){if(!ctx.isAdmin)return;if(!await ctx.confirmAction('Void financial entry','The entry stays in history and is excluded from balances and reports. Record a replacement separately.','Void entry'))return;try{await ctx.db.ref('notes/'+id).update({voided:true,voidedAt:now(),voidedBy:ctx.user.uid});await ctx.audit('void rental '+k,id);ctx.flash('Entry voided.')}catch(err){ctx.flash(err.message,'error')}}
function postRent(){ctx.modal('Post monthly rent',`<form id="postRentForm"><label>Rent month</label><input name="month" type="month" required value="${today().slice(0,7)}"><label class="expense-check"><input name="prorate" type="checkbox" checked> Prorate partial first and last months</label><p class="muted">Review the total before posting. Existing monthly charges are skipped, including voided charges. Add a replacement manually after voiding.</p><div class="actions end"><button class="btn">Review charges</button></div><p id="postRentError" class="error"></p></form>`);$('postRentForm').onsubmit=async ev=>{ev.preventDefault();const btn=ev.target.querySelector('button');btn.disabled=true;try{const fd=new FormData(ev.target),month=fd.get('month');if(!C.dateOk(month+'-01'))throw Error('Choose a valid month.');const planned=rows('leases').map(l=>({l,charge:C.monthlyCharge(l,month,fd.has('prorate')),id:'rental_charge_'+l.id+'_'+month})).filter(x=>x.charge&&x.charge.amountCents>0&&!ctx.notes[x.id]);if(!planned.length){ctx.flash('No new charges: leases do not cover this month or charges already exist.');ctx.closeModal();return}if(!await ctx.confirmAction('Confirm rent posting',`Post ${planned.length} charges for ${month}, totaling ${money(planned.reduce((s,x)=>s+x.charge.amountCents,0))}? Partial-month charges use occupied calendar days.`,'Post rent')){btn.disabled=false;return}let added=0;for(const {l,charge,id} of planned){const result=await ctx.db.ref('notes/'+id).transaction(existing=>existing===null?{...charge,leaseId:l.id,propertyId:l.propertyId,kind:'Rent',description:'Monthly rent '+month,entityType:types.charges,createdAt:now(),updatedBy:ctx.user.uid}:undefined);if(result.committed)added++}await ctx.audit('post rental rent',month+' '+added+' charges');ctx.closeModal();ctx.flash(added+' rent charges posted.')}catch(err){$('postRentError').textContent=err.message;btn.disabled=false}}}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000)}
function reports(){$('rentalBody').innerHTML=`<section class="card"><h3>Portfolio reports & backup</h3><p>Excel includes directories, current rent roll, charges, payments, deposit balances, work orders, and rental expenses. Full JSON backups preserve record IDs and links.</p><div class="actions"><button class="btn" id="rentalExcel">Export Excel workbook</button><button class="btn secondary" id="rentalBackup">Download full backup</button></div></section>${ctx.canWrite?'<section class="card"><h3>Restore / merge rental backup</h3><p>Import a BBCOR rental JSON backup. Matching IDs are updated; current records are never deleted. Export a backup before merging.</p><input type="file" id="rentalImportFile" accept=".json"><button class="btn" id="rentalImport">Review import</button></section>':''}<p class="muted">Rental expenses have their own ledger; they are not automatically duplicated in Expense Center. Excel is for reporting; use JSON for a complete restore.</p>`;$('rentalBackup').onclick=()=>download(new Blob([JSON.stringify({format:'BBCOR_RENTAL_TRANSFER_V1',exportedAt:now(),...Object.fromEntries(Object.keys(types).map(k=>[k,rows(k)]))})],{type:'application/json'}),'BBCOR_RENTAL_BACKUP_'+today()+'.json');$('rentalExcel').onclick=()=>{const wb=XLSX.utils.book_new();for(const k of Object.keys(types)){const a=rows(k).map(r=>Object.fromEntries(Object.entries(r).map(([key,value])=>[key.endsWith('Cents')?key.replace('Cents',' USD'):key,key.endsWith('Cents')?Number(value)/100:value])));XLSX.utils.book_append_sheet(wb,a.length?XLSX.utils.json_to_sheet(a):XLSX.utils.aoa_to_sheet([['No records']]),k)}const roll=rows('leases').map(l=>({Property:find('properties',l.propertyId)?.name,Unit:find('units',l.unitId)?.name,Tenant:find('tenants',l.tenantId)?.name,Status:l.status,'Active today':C.active(l,today()),'Monthly rent USD':l.rentCents/100,'Balance USD':C.leaseBalance(l.id,rows('charges'),rows('payments'),today()).balanceCents/100,'Past due USD':C.leaseBalance(l.id,rows('charges'),rows('payments'),today()).pastDueCents/100,'Deposit held USD':C.deposits(l.id,rows('payments'),today())/100,'As of':today()}));XLSX.utils.book_append_sheet(wb,roll.length?XLSX.utils.json_to_sheet(roll):XLSX.utils.aoa_to_sheet([['No leases']]),'Rent roll');const months=[...new Set([...rows('payments'),...rows('expenses')].map(r=>r.date.slice(0,7)))].sort();const cashRows=months.flatMap(month=>rows('properties').map(p=>{const flow=C.cashflow(rows('payments'),rows('expenses'),month+'-01',month+'-31',p.id);return {Month:month,Property:p.name,'Rent received USD':flow.incomeCents/100,'Expenses USD':flow.expenseCents/100,'Net cash flow USD':flow.netCents/100}}));XLSX.utils.book_append_sheet(wb,cashRows.length?XLSX.utils.json_to_sheet(cashRows):XLSX.utils.aoa_to_sheet([['No cash transactions']]),'Cash flow');XLSX.writeFile(wb,'BBCOR_RENTAL_REPORT_'+today()+'.xlsx')};if(ctx.canWrite)$('rentalImport').onclick=importBackup}
async function importBackup(){try{const file=$('rentalImportFile').files[0];if(!file)throw Error('Choose a rental backup JSON.');if(file.size>20*1024*1024)throw Error('Backup exceeds 20 MB.');const obj=JSON.parse(await file.text());if(obj.format!=='BBCOR_RENTAL_TRANSFER_V1')throw Error('Unsupported backup format.');const records={},updates={};for(const k of Object.keys(types)){if(!Array.isArray(obj[k]))throw Error('Missing '+k+' collection.');for(const r of obj[k]){if(!r||typeof r!=='object'||!/^rental_[A-Za-z0-9_-]{1,180}$/.test(r.id)||records[r.id])throw Error('Invalid or duplicate rental ID.');if(ctx.notes[r.id]&&ctx.notes[r.id].entityType!==types[k])throw Error('Record type conflict.');records[r.id]={...r,entityType:types[k]}}}
const original=ctx.notes;ctx.notes={...original,...records};try{for(const k of Object.keys(types))for(const r of obj[k]){validate(k,r,r.id);if(['leases','charges','payments'].includes(k)){const parent=k==='leases'?find('units',r.unitId):find('leases',r.leaseId);if(r.propertyId!==parent?.propertyId)throw Error('Property relationship mismatch.')}if(r.voided&&!ctx.isAdmin)throw Error('An administrator must restore backups containing voided entries.');const existing=original[r.id];if(existing&&['charges','payments','expenses'].includes(k)&&!equalRecords(existing,records[r.id]))throw Error('A posted entry already exists with this ID. Financial history cannot be overwritten; use a backup with unchanged entries.');if(existing&&k==='leases'&&(existing.unitId!==r.unitId||existing.tenantId!==r.tenantId)&&[...rows('charges'),...rows('payments')].some(t=>t.leaseId===r.id))throw Error('A lease with transactions cannot change unit or tenant.');if(existing&&k==='units'&&existing.propertyId!==r.propertyId&&rows('leases').some(l=>l.unitId===r.id))throw Error('A leased unit cannot change property.');const {id,...record}=records[r.id];updates[id]=record}}finally{ctx.notes=original}
if(!await ctx.confirmAction('Merge rental backup',`Merge ${Object.keys(updates).length} records from ${file.name}? This preserves other centers and does not delete existing records.`,'Import'))return;await ctx.db.ref('notes').update(updates);await ctx.audit('import rental backup',file.name);ctx.flash('Rental portfolio backup merged.')}catch(err){ctx.flash('Import stopped: '+err.message,'error')}}
window.BBCORRentals={render};
})();
