const test=require('node:test'),assert=require('node:assert/strict'),core=require('../buyer-core.js');
const p={company:'AIC Industrial',aliases:['AIC Ventures'],canonicalDomain:'aicindustrial.com',sourceKey:'aicindustrial.com',sourceUrl:'https://aicindustrial.com/acquisitions/',sourceVersion:'v2',whyFits:'New source evidence'};
test('source aliases and official domain reuse existing id and keep private workflow',()=>{const rows=core.merged({old:{entityType:'buyer_prospect',company:'AIC Industrial / AIC Ventures, Inc.',sourceUrl:p.sourceUrl,stage:'Declined',internalNotes:'Private',sourceVersion:'v1'}},{prospects:[p]});assert.equal(rows.length,1);assert.equal(rows[0].id,'old');assert.equal(rows[0].stage,'Declined');assert.equal(rows[0].internalNotes,'Private');assert.equal(rows[0].sourceNeedsReview,true)});
test('new source is research only and contact locked',()=>{const [r]=core.merged({}, {prospects:[p]});assert.equal(r.feedOnly,true);assert.equal(r.stage,'Research only');assert.equal(r.outreachStatus,core.hold);assert.equal(r.propertyMatch,'Unconfirmed — review acquisition criteria')});
test('review retains latest concurrent private fields, source cannot authorize outreach',()=>{const current={entityType:'buyer_prospect',stage:'In discussion',internalNotes:'Concurrent edit',priority:'High',propertyMatch:'Reviewed match',outreachStatus:'Hold',custom:'Keep'};const r=core.reviewed(current,{...p,stage:'Contacted',internalNotes:'overwrite'},'reviewer','now');assert.equal(r.internalNotes,'Concurrent edit');assert.equal(r.stage,'In discussion');assert.equal(r.custom,'Keep');assert.equal(r.outreachStatus,'Hold');assert.equal(r.sourceReviewedBy,'reviewer')});
test('ambiguous duplicate identities do not create another record',()=>{const notes={a:{entityType:'buyer_prospect',company:p.company},b:{entityType:'buyer_prospect',company:p.company}};assert.equal(core.merged(notes,{prospects:[p]}).length,2)});
test('identity conflict aborts',()=>assert.throws(()=>core.reviewed({entityType:'property'},p,'u','now')));

test('saving a private note is not source approval',()=>{const rows=core.merged({saved:{entityType:'buyer_prospect',company:p.company,sourceVersion:p.sourceVersion,internalNotes:'Note only'}},{prospects:[p]});assert.equal(rows[0].sourceNeedsReview,true)});
